In [ ]:
import numpy as np
import pandas as pd

In [ ]:

details = {
    'name' : ['akash','rohit','dhruv'],
    'age' : [18,18,18],
    'enrollment' : ['216270307019', '216270307012','216270307054']
}
print(pd.DataFrame(details,columns=['name','age','enrollment']))

In [ ]:
details = {
    'name' : ['akash','rohit','dhruv'],
    'age' : [18,18,18],
    'enrollment' : ['216270307019', '216270307012','216270307054']
}
print(pd.DataFrame(details,columns=['name','age','enrollment']).sort_values(by =['enrollment'])),

In [ ]:
details = {
    'name' : ['akash','rohit','dhruv'],
    'age' : [18,18,18],
    'enrollment' : ['216270307019', '216270307012','216270307054']
}
print(pd.DataFrame(details,columns=['name','age','enrollment']).drop(['enrollment'],axis=1)),

In [ ]:
import pandas as pd

d1 = {'Name': ['Pankaj', 'Meghna'], 'ID': [1, 2], 'Role': ['CEO', 'CTO']}

df = pd.DataFrame(d1)

print('DataFrame:\n', df)

# default CSV
csv_data = df.to_csv(sep='\t')
print('\nCSV String:\n', csv_data)